export const FETCH_USER_INIT = 'FETCH_USER_INIT'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_CATEGORY_INIT = 'FETCH_CATEGORY_INIT'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'

export const SET_SEARCH = 'SET_SEARCH'

export const SET_PAGE = 'SET_PAGE'

export const FILTER_PRODUCT_BY_CATEGORY = 'FILTER_PRODUCT_BY_CATEGORY'
export const PAGINATE_PRODUCTS = 'PAGINATE_PRODUCTS'
export const FETCH_PRODUCT_INIT = 'FETCH_PRODUCT_DESCRIPTION_INIT'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'
export const FETCH_PRODUCT_DESCRIPTION_INIT = 'FETCH_PRODUCT_DESCRIPTION_INIT'
export const FETCH_PRODUCT_DESCRIPTION_SUCCESS = 'FETCH_PRODUCT_DESCRIPTION_SUCCESS'
export const FETCH_PRODUCT_DESCRIPTION_ERROR = 'FETCH_PRODUCT_DESCRIPTION_ERROR'

export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY'
export const EXPAND_CATEGORY_ITEM = 'EXPAND_CATEGORY_ITEM'

export const FETCH_CART_INIT = 'FETCH_CART_INIT'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR'

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'

export const FETCH_ORDER_INIT = 'FETCH_ORDER_INIT'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR'