export const DISPLAY_CART_DATA = 'DISPLAY_CART_DATA';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const PROCEED_CHECKOUT = 'PROCEED_CHECKOUT';
export const UPDATE_CART='UPDATE_CART';
export const DISPLAY_STATUS_MESSAGE='DISPLAY_STATUS_MESSAGE';
export const UPDATE_PRICE="UPDATE_PRICE";
export const ORDER_UPDATE="ORDER_UPDATE";