export const DISPLAY_PRODUCTS_LIST = 'DISPLAY_PRODUCTS_LIST';
export const DISPLAY_CATEGORIES = 'DISPLAY_CATEGORIES';
export const FILTER_PRODUCTS_BY_CATEGORY='FILTER_PRODUCTS_BY_CATEGORY';
export const DISPLAY_PAGINATION_RESULTS='DISPLAY_PAGINATION_RESULTS';
export const RESET_FILTER='RESET_FILTER';